module.exports = ({
   FETCH_RECIPES: 'FETCH_RECIPES',
   UPDATE_SEARCH_TERM: 'UPDATE_SEARCH_TERM',
   SHOW_ERROR: 'SHOW_ERROR',
   HIDE_ERROR: 'HIDE_ERROR',
   SHOW_WELCOME: 'SHOW_WELCOME',
   HIDE_WELCOME: 'HIDE_WELCOME',
});